[versions]
agp = "8.10.1"
kotlin = "2.1.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
lottie = "6.6.7"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
googleService = "4.4.2"
firebase = "33.15.0"
firebaseCrashlytics = "3.0.4"
retrofit = "3.0.0"
okhttp = "5.0.0-alpha.16"
glide = "4.16.0"
lingver = "1.3.0"
shimmer = "0.5.0"
lifeCycle = "2.9.1"
coroutines = "1.10.2"
uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.3.4"
userMessagingPlatform = "3.2.0"

[libraries]
# Test libraries
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Material design
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Android X
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifeCycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifeCycle" }

# Coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }

# PlayServices Ads and AppUpdate
play-services-ads = { module = "com.google.android.gms:play-services-ads", version = "24.4.0" }
app-update = { module = "com.google.android.play:app-update-ktx", version = "2.1.0" }
review-manager = { module = "com.google.android.play:review-ktx", version = "2.0.2" }

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

# Glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

# Lingver
lingver = { module = "com.github.YarikSOffice:lingver", version.ref = "lingver" }

# Shimmer
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }

# Beckmark
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }

# Consent GDPR
user-messaging-platform = { module = "com.google.android.ump:user-messaging-platform", version.ref = "userMessagingPlatform" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleService = { id = "com.google.gms.google-services" , version.ref = "googleService" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
android-test = { id = "com.android.test", version.ref = "agp" }

